name: Update Blog Posts
on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 수동 실행을 위한 설정 추가

permissions:
  contents: write

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'JoohyungDev'
        git config --global user.email 'jhp20c@gmail.com'
        git push origin

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py



